POST http://localhost:3000/courses
Content-Type: application/json

{
  "title": "Curso de PostgreSQL2",
  "description": "baita curso"
}

###

GET http://localhost:3000/courses?orderBy=title

###

GET http://localhost:3000/courses?search=react

###

GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/c21b3ec3-3e97-40b1-a5de-d9e017d694ae

###

DELETE http://localhost:3000/courses/2